# ICU Deterioration Prediction
This project ims to predict early signs of patient deterioration in ICU using simple clinical features such as age,heart rate,and blood pressure.

## ICU Deterioration Prediction

This project aims to predict early signs of patient deterioration in ICU using simple clinical features such as age,heart rate,and blood pressure.

## Clinical Importance
Early detection of patient deterioration in ICU can significantly reduce mortality and improve outcomes.
This project demonstrates a simple machine learning approach to identify high-risk patients using basic vital signs.

## Model Comparison
Two machine learning models were used:
- Logistic Regression: A simple and interpretable model for binary classification.
- Random Forest: A more complex model that can capture non-linear relationships.
- The performance of both models was evaluated using accuracy.

## Implementation
This section demonstrates the step-by-step implementation of a machine learning pipeline for predicting ICU patient deterioration.
The workflow includes data preparation, model training using Logistic Regression and Random Forest, and performance evaluation using accuracy.

### Data Preparation

In [1]:
import pandas as pd

In [2]:
data = {
        "Age": [65, 72, 50, 80, 60] ,
        "HeartRate": [110, 95, 88, 120, 100] ,
        "BloodPressure": [90, 100, 110, 85, 95] ,
        "Outcome": [1, 0, 0, 1, 1]
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

   Age  HeartRate  BloodPressure  Outcome
0   65        110             90        1
1   72         95            100        0
2   50         88            110        0
3   80        120             85        1
4   60        100             95        1

### Model Training

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [6]:
X = df[["Age", "HeartRate","BloodPressure"]]
Y = df["Outcome"]

In [7]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [8]:
model = LogisticRegression()
model.fit(X_train, Y_train)

LogisticRegression()

In [9]:
model.predict(X_test)

array([1])

In [10]:
model.predict([[70, 115, 85]])

C:\Users\klobn\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1])

In [11]:
import pandas as pd
new_patient = pd.DataFrame({
    "Age": [70],
    "HeartRate": [115],
    "BloodPressure": [85]
})
model.predict(New_patient)

NameError: name 'New_patient' is not defined

In [ ]:
import pandas as pd
new_patient = pd.DataFrame({
    "Age": [70],
    "HeartRate": [115],
    "BloodPressure": [85]
})
model.predict(new_patient)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier()
rf_model.fit(X_train, Y_train)
rf_model.predict(new_patient)

In [ ]:
print("Logistic Regression Prediction:", model.predict(new_patient))
print("Random Forest Prediction:", rf_model.predict(new_patient))

### Evaluation

In [ ]:
from sklearn.metrics import accuracy_score
log_pred = model.predict(X_test)
rf_pred = rf_model.predict(X_test)
print("Logistic Regression Accuracy:", accuracy_score(Y_test, log_pred))
print("Random Forest Accuracy:", accuracy_score(Y_test, rf_pred))

## Results
- Logistic Regression accuracy: 1.0
- Random Forest accuracy: 0.0
  Note: Due to the very small dataset,results may not generalize well.

## Results
- Logistic Regression accuracy: 1.0
- Random Forest accuracy: 0.0
- **Note:** Due to the very small dataset, results may not generalize well.

## Conclusion
This project demonstrates a simple approach to predicting ICU patient deterioration using basic clinical features.

Although the dataset is small,the workflow shows how such models can be applied in clinical settings.

Future improvements could include:

- Using larger real-world datasets
- Adding more clinical features
- Improving model performance

In [14]:
import pandas as pd

In [15]:
df.columns

Index(['Age', 'HeartRate', 'BloodPressure', 'Outcome'], dtype='object')

In [16]:
def calculate_risk(row):
    score = 0

    # Age
    if row['Age'] > 60:
        score += 2

    # Heart Rate
    if row['HeartRate'] > 100:
        score += 2

    # Blood Pressure (low)
    if row['BloodPressure'] < 90:
        score += 2

    return score


df['risk_score'] = df.apply(calculate_risk, axis=1)


def classify_risk(score):
    if score <= 2:
        return "Low Risk"
    elif score <= 4:
        return "Medium Risk"
    else:
        return "High Risk"


df['risk_level'] = df['risk_score'].apply(classify_risk)

df[['Age', 'HeartRate', 'BloodPressure', 'risk_score', 'risk_level']].head()

   Age  HeartRate  BloodPressure  risk_score   risk_level
0   65        110             90           4  Medium Risk
1   72         95            100           2     Low Risk
2   50         88            110           0     Low Risk
3   80        120             85           6    High Risk
4   60        100             95           0     Low Risk

In [17]:
def calculate_risk(row):
    score = 0

    # Age
    if row['Age'] > 65:
        score += 2

    # Heart Rate
    if row['HeartRate'] > 110:
        score += 2
    elif row['HeartRate'] > 100:
        score += 1

    # Blood Pressure
    if row['BloodPressure'] < 85:
        score += 2
    elif row['BloodPressure'] < 95:
        score += 1

    return score

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# Features
X = df[['Age', 'HeartRate', 'BloodPressure']]

# Target
y = df['Outcome']

# Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Model
model = LogisticRegression()
model.fit(X_train, y_train)

# Accuracy
print(model.score(X_test, y_test))

1.0

In [19]:
print(model.coef_)

[[-0.10485617  0.30633633 -0.25498391]]

In [20]:
df[['risk_score', 'Outcome']].head(10)

   risk_score  Outcome
0           4        1
1           2        0
2           0        0
3           6        1
4           0        1

In [23]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00         1

    accuracy                           1.00         1
   macro avg       1.00      1.00      1.00         1
weighted avg       1.00      1.00      1.00         1

In [32]:
import pandas as pd

patients = pd.read_csv("C:/Users/klobn/OneDrive/Desktop/ATLAS/data/mimic-demo/hosp/patients.csv.gz")

patients.head()

   subject_id gender  anchor_age  anchor_year anchor_year_group         dod
0    10014729      F          21         2125       2011 - 2013         NaN
1    10003400      F          72         2134       2011 - 2013  2137-09-02
2    10002428      F          80         2155       2011 - 2013         NaN
3    10032725      F          38         2143       2011 - 2013  2143-03-30
4    10027445      F          48         2142       2011 - 2013  2146-02-09

In [33]:
import pandas as pd

icu = pd.read_csv("C:/Users/klobn/OneDrive/Desktop/ATLAS/data/mimic-demo/icu/icustays.csv.gz")

icu.head()

,subject_id,hadm_id,stay_id,first_careunit,last_careunit,intime,outtime,los
0,10018328,23786647,31269608,Neuro Stepdown,Neuro Stepdown,2154-04-24 23:03:44,2154-05-02 15:55:21,7.702512
1,10020187,24104168,37509585,Neuro Surgical Intensive Care Unit (Neuro SICU),Neuro Stepdown,2169-01-15 04:56:00,2169-01-20 15:47:50,5.452662
2,10020187,26842957,32554129,Neuro Intermediate,Neuro Intermediate,2170-02-24 18:18:46,2170-02-25 15:15:26,0.872685
3,10012853,27882036,31338022,Trauma SICU (TSICU),Trauma SICU (TSICU),2176-11-26 02:34:49,2176-11-29 20:58:54,3.766725
4,10020740,25826145,32145159,Trauma SICU (TSICU),Trauma SICU (TSICU),2150-06-03 20:12:32,2150-06-04 21:05:58,1.037106

In [34]:
df = patients.merge(icu, on="subject_id")

df.head()

,subject_id,gender,anchor_age,anchor_year,anchor_year_group,dod,hadm_id,stay_id,first_careunit,last_careunit,intime,outtime,los
0,10014729,F,21,2125,2011 - 2013,NaN,28889419,33558396,Cardiac Vascular Intensive Care Unit (CVICU),Cardiac Vascular Intensive Care Unit (CVICU),2125-02-27 10:03:08,2125-03-01 21:21:37,2.471169
1,10003400,F,72,2134,2011 - 2013,2137-09-02,23559586,38383343,Coronary Care Unit (CCU),Medical Intensive Care Unit (MICU),2137-08-17 17:36:37,2137-09-02 19:17:11,16.069838
2,10003400,F,72,2134,2011 - 2013,2137-09-02,23559586,34577403,Medical/Surgical Intensive Care Unit (MICU/SICU),Medical/Surgical Intensive Care Unit (MICU/SICU),2137-08-10 19:54:51,2137-08-13 17:54:54,2.916701
3,10003400,F,72,2134,2011 - 2013,2137-09-02,20214994,32128372,Medical/Surgical Intensive Care Unit (MICU/SICU),Medical/Surgical Intensive Care Unit (MICU/SICU),2137-02-25 23:37:19,2137-03-10 21:29:36,12.911308
4,10002428,F,80,2155,2011 - 2013,NaN,20321825,34807493,Medical Intensive Care Unit (MICU),Medical Intensive Care Unit (MICU),2156-04-30 21:53:00,2156-05-02 22:27:20,2.023843

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   subject_id         140 non-null    int64
 1   gender             140 non-null    object
 2   anchor_age         140 non-null    int64
 3   anchor_year        140 non-null    int64
 4   anchor_year_group  140 non-null    object
 5   dod                49 non-null     object
 6   hadm_id            140 non-null    int64
 7   stay_id            140 non-null    int64
 8   first_careunit     140 non-null    object
 9   last_careunit      140 non-null    object
 10  intime             140 non-null    object
 11  outtime            140 non-null    object
 12  los                140 non-null    float64
dtypes: float64(1), int64(5), object(7)
memory usage: 14.3+ KB

In [36]:
df['outcome'] = df['dod'].notnull().astype(int)

df['outcome'].value_counts()

outcome
0    91
1    49
Name: count, dtype: int64

In [37]:
df.groupby('outcome')['los'].mean()

outcome
0    3.213476
1    4.544627
Name: los, dtype: float64

In [38]:
df.groupby('outcome')['anchor_age'].mean()

outcome
0    59.32967
1    67.00000
Name: anchor_age, dtype: float64

In [39]:
df.groupby(['first_careunit', 'outcome']).size()

first_careunit                                    outcome
Cardiac Vascular Intensive Care Unit (CVICU)      0          23
                                                  1           2
Coronary Care Unit (CCU)                          0           6
                                                  1           7
Medical Intensive Care Unit (MICU)                0          14
                                                  1          15
Medical/Surgical Intensive Care Unit (MICU/SICU)  0          13
                                                  1          10
Neuro Intermediate                                0           1
Neuro Stepdown                                    0           1
Neuro Surgical Intensive Care Unit (Neuro SICU)   0           2
                                                  1           1
Surgical Intensive Care Unit (SICU)               0          20
                                                  1           9
Trauma SICU (TSICU)                               0          11
                                                  1           5
dtype: int64

In [40]:
def atlas_risk_score(row):
    score = 0
    
    # Age score
    if row['anchor_age'] >= 75:
        score += 2
    elif row['anchor_age'] >= 65:
        score += 1

    # ICU type score
    unit = str(row['first_careunit'])
    
    if 'CCU' in unit:
        score += 2
    elif 'MICU' in unit:
        score += 2
    elif 'SICU' in unit or 'TSICU' in unit:
        score += 1

    return score


def atlas_risk_level(score):
    if score <= 1:
        return "Low Risk"
    elif score <= 3:
        return "Medium Risk"
    else:
        return "High Risk"


df['atlas_score'] = df.apply(atlas_risk_score, axis=1)
df['atlas_risk'] = df['atlas_score'].apply(atlas_risk_level)

df[['subject_id', 'anchor_age', 'first_careunit', 'atlas_score', 'atlas_risk', 'outcome']].head(10)

,subject_id,anchor_age,first_careunit,atlas_score,atlas_risk,outcome
0,10014729,21,Cardiac Vascular Intensive Care Unit (CVICU),0,Low Risk,0
1,10003400,72,Coronary Care Unit (CCU),3,Medium Risk,1
2,10003400,72,Medical/Surgical Intensive Care Unit (MICU/SICU),3,Medium Risk,1
3,10003400,72,Medical/Surgical Intensive Care Unit (MICU/SICU),3,Medium Risk,1
4,10002428,80,Medical Intensive Care Unit (MICU),4,High Risk,0
5,10002428,80,Medical Intensive Care Unit (MICU),4,High Risk,0
6,10002428,80,Medical Intensive Care Unit (MICU),4,High Risk,0
7,10002428,80,Surgical Intensive Care Unit (SICU),3,Medium Risk,0
8,10032725,38,Medical/Surgical Intensive Care Unit (MICU/SICU),2,Medium Risk,1
9,10027445,48,Coronary Care Unit (CCU),2,Medium Risk,1

In [41]:
df['atlas_risk'].value_counts()

atlas_risk
Medium Risk    79
Low Risk       46
High Risk      15
Name: count, dtype: int64

In [42]:
df.groupby('atlas_risk')['outcome'].mean()

atlas_risk
High Risk      0.400000
Low Risk       0.108696
Medium Risk    0.481013
Name: outcome, dtype: float64

In [43]:
elif score <= 2:
    return "Medium Risk"

SyntaxError: invalid syntax (164063518.py, line 1)

In [44]:
def atlas_risk_level(score):
    if score <= 1:
        return "Low Risk"
    elif score <= 2:
        return "Medium Risk"
    else:
        return "High Risk"

In [45]:
df['atlas_risk'] = df['atlas_score'].apply(atlas_risk_level)

df.groupby('atlas_risk')['outcome'].mean()

atlas_risk
High Risk      0.657895
Low Risk       0.108696
Medium Risk    0.339286
Name: outcome, dtype: float64

In [46]:
df['atlas_risk'].value_counts()

atlas_risk
Medium Risk    56
Low Risk       46
High Risk      38
Name: count, dtype: int64

In [47]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

# Features (مبدئيًا)
X = df[['anchor_age']]
X = pd.get_dummies(df[['anchor_age','first_careunit']], drop_first=True)

y = df['outcome']

# تقسيم
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# الموديل
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# التوقع
y_pred = model.predict(X_test)

# النتيجة
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.76      0.80      0.78        20
           1       0.43      0.38      0.40         8

    accuracy                           0.68        28
   macro avg       0.60      0.59      0.59        28
weighted avg       0.67      0.68      0.67        28

In [48]:
df['icu_count'] = df.groupby('subject_id')['stay_id'].transform('count')

In [49]:
df[['subject_id', 'stay_id', 'icu_count']].head(10)

   subject_id   stay_id  icu_count
0    10014729  33558396          1
1    10003400  38383343          3
2    10003400  34577403          3
3    10003400  32128372          3
4    10002428  34807493          4
5    10002428  38875437          4
6    10002428  33987268          4
7    10002428  35479615          4
8    10032725  30101877          1
9    10027445  36084484          2

In [50]:
df.groupby('outcome')['icu_count'].mean()

outcome
0    1.791209
1    1.938776
Name: icu_count, dtype: float64

In [51]:
def icu_risk_level(x):
    if x == 1:
        return "Low"
    elif x <= 2:
        return "Medium"
    else:
        return "High"

df['icu_risk'] = df['icu_count'].apply(icu_risk_level)

In [52]:
df.groupby('icu_risk')['outcome'].mean()

icu_risk
High      0.441176
Low       0.243243
Medium    0.500000
Name: outcome, dtype: float64

In [53]:
df['intime'] = pd.to_datetime(df['intime'])
df['outtime'] = pd.to_datetime(df['outtime'])

In [54]:
df['icu_hours'] = (df['outtime'] - df['intime']).dt.total_seconds() / 3600

In [55]:
df.groupby('outcome')['icu_hours'].mean()

outcome
0     77.123431
1    109.071049
Name: icu_hours, dtype: float64

In [56]:
def icu_time_risk(x):
    if x < 24:
        return "Short"
    elif x < 72:
        return "Medium"
    else:
        return "Long"

df['icu_time_risk'] = df['icu_hours'].apply(icu_time_risk)

In [57]:
df.groupby('icu_time_risk')['outcome'].mean()

icu_time_risk
Long      0.400000
Medium    0.290323
Short     0.391304
Name: outcome, dtype: float64

In [58]:
# icu_count (موجود)
# icu_time_risk (موجود)

# new feature
df['is_extreme'] = df['icu_time_risk'].apply(lambda x: 1 if x in ['Short', 'Long'] else 0)

In [59]:
X = df[['anchor_age', 'icu_count', 'is_extreme']]

# إضافة نوع ICU
X = pd.get_dummies(pd.concat([X, df[['first_careunit']]], axis=1), drop_first=True)

y = df['outcome']

In [60]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [61]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [62]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.75      0.79        20
           1       0.50      0.62      0.56         8

    accuracy                           0.71        28
   macro avg       0.67      0.69      0.67        28
weighted avg       0.74      0.71      0.72        28

In [63]:
df = df.sort_values(['subject_id', 'intime'])

In [64]:
df['prev_intime'] = df.groupby('subject_id')['intime'].shift(1)
df['hours_since_prev_icu'] = (df['intime'] - df['prev_intime']).dt.total_seconds() / 3600

In [65]:
df[['subject_id', 'stay_id', 'intime', 'prev_intime', 'hours_since_prev_icu']].head(15)

,subject_id,stay_id,intime,prev_intime,hours_since_prev_icu
39,10000032,39553978,2180-07-23 14:00:00,NaT,NaN
19,10001217,37067082,2157-11-20 19:18:02,NaT,NaN
20,10001217,34592300,2157-12-19 15:42:24,2157-11-20 19:18:02,692.406111
13,10001725,31205490,2110-04-11 15:52:22,NaT,NaN
6,10002428,33987268,2156-04-12 16:24:18,NaT,NaN
5,10002428,38875437,2156-04-19 18:11:19,2156-04-12 16:24:18,169.783611
4,10002428,34807493,2156-04-30 21:53:00,2156-04-19 18:11:19,267.694722
7,10002428,35479615,2156-05-11 14:49:34,2156-04-30 21:53:00,256.942778
118,10002495,36753294,2141-05-22 20:18:01,NaT,NaN
27,10002930,37049133,2196-04-14 13:40:00,NaT,NaN
28,10002930,35629889,2198-04-17 21:24:00,2196-04-14 13:40:00,17599.733333
67,10003046,35514836,2154-01-02 15:57:15,NaT,NaN
3,10003400,32128372,2137-02-25 23:37:19,NaT,NaN
2,10003400,34577403,2137-08-10 19:54:51,2137-02-25 23:37:19,3980.292222
1,10003400,38383343,2137-08-17 17:36:37,2137-08-10 19:54:51,165.696111

In [66]:
df.groupby('outcome')['hours_since_prev_icu'].mean()

outcome
0    7105.696465
1    5643.269738
Name: hours_since_prev_icu, dtype: float64

In [67]:
df['rapid_readmission'] = (df['hours_since_prev_icu'] <= 48).astype(int)
df['rapid_readmission'] = df['rapid_readmission'].fillna(0)

df.groupby('rapid_readmission')['outcome'].mean()

rapid_readmission
0    0.34058
1    1.00000
Name: outcome, dtype: float64